# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a207d7aa6453b0ea4a66235586bf7dec08814e742c2b58c71c49eaee05ebfdfac4b7659a139a9bc2e517a8521a68a3ff5050ed33f75dd229e4fc45fad2cc4709

test:
  secret_key_base: 6ccfe462d1967f90990c5ccb64696643f473ae8272374c8fb259309c477cca9efe1162e836ed68ca808c7ac71193f639cb20d8aca7ba90f2e6e187cc784b7f3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
